### ISSUE TITLE
Trouble compiling, missing array.h

### ISSUE THREAD

**Issue by haimiko** [ngraziano/LMICPP-Arduino#14]
Having issues locating the correct array.h library.
lib\LMICPP-Arduino-master\src/lmic/../aes/../lmic/lorabase.h:60:26: error: 'array' in namespace 'std' does not name a template type

**Comment by ngraziano** [comment]
Hi,
If it is an atmelavr board did you the stl lib like in example: 

```ini
lib_deps =
  ciband/avr_stl
```

for arm and esp32 stl lib should be available by default.

**Comment by haimiko** [comment]
That did it.  Thank you.   Now to set the frequency to 915MHz.  I tried
defining CFG_us915, per Arduino LMIC docs but that didn't help.

**Comment by haimiko** [comment]
Doh.  Found it. :)
