### ISSUE TITLE
Great Library .. can i help?

### ISSUE THREAD

**Issue by daeynasvistas** [ngraziano/LMICPP-Arduino#17]
Ok. Let me start the post by saying that this library seems great.
Download, use platformio .. build upload.. first time .. first join.... Txack with ClassC no problem at all..

![image](https://user-images.githubusercontent.com/2634610/146431050-0cbc7925-86ca-4449-a74d-7fa90e1991df.png)

LinkAdrReq also with no problem..
![image](https://user-images.githubusercontent.com/2634610/146431411-d10ca38d-f102-4f96-bd6f-d8a16ad26680.png)

it's so rare that all goes well.. that i want to post the state of happiness i'm in at the moment.

I use EU868 with ClassC OTAA.
With devBoard TTGO v1 and custom Board ESP32 pico Sx1276

**do you need some help on testing some features?**

**Comment by ngraziano** [comment]
Hi, 

Happy that this is working for you. What lorawan network are you using ? (I do not recognize the management console)

If you can send specific MAC command you can try to change DutyCycle or other parameter. (I only use TTN and I can't control all the command sent by the network)
