### ISSUE TITLE
Cant compile LMICPP-Arduino

### ISSUE THREAD

**Issue by mkbehbeh** [ngraziano/LMICPP-Arduino#2]
When I try to compile the LMICPP-Arduino, I get an error that #include <algorithm> file is not found.  I googled it and it sounds like you are using the STD for AVR so I followed the directions to include that, unfortunately, that didnt work either.  

are there any changes to the configuration that needs to happen other then copying the master folder into the libary section and modifying the LMIC configs?  I have been using the MCCI fork, but have ran into problems with the AVR powersavings and found your TTN post 

I would like to test out your library, but I cant even get it to compile.

Thanks, 
Mark

**Comment by ngraziano** [comment]
Hi
For compilation I use platformio (which allow to use Arduino library and board) and it is working very well. 
I haven't try to use the Arduino IDE for a while and I just check it will not work.

With platformio copy directory examples/balise where you want, and open it with platfomio create a file lorakeys.h like explain in the README of the sample and compile it, it will download automatically the necessary library.
