### ISSUE TITLE
ESP8266 support

### ISSUE THREAD

**Issue by alexcorvis84** [ngraziano/LMICPP-Arduino#21]
Hi @ngraziano, thanks for sharing the library.

I'm wondering if you could do it compatible with ESP8266. As far as I've checked, there's an [RTCMemory library](https://github.com/fabianoriccardi/rtcmemory) compatible that would help to make it possible... I'm using an Wemos D1 mini + RFM95W & would like to use this 'variant' version in case.

I'm looking forward to hearing from you soon. Many thanks in advance.

**Comment by ngraziano** [comment]
It should be compatible with ESP8266 now (it is compiling). 

If you want to save the state in RTC Memory, you have to take a look at esp32-deepsleep and save yourself the buffer "saveState" but i'm not sure there is enough space in the esp8266 RTC memory. It may not work.

I have no board to test.

**Comment by daeynasvistas** [comment]
> It should be compatible with ESP8266 now (it is compiling).
> 
> If you want to save the state in RTC Memory, you have to take a look at esp32-deepsleep and save yourself the buffer "saveState" but i'm not sure there is enough space in the esp8266 RTC memory. It may not work.
> 
> I have no board to test.

Its working with ESP8266 (simple.. Join, send and receive)
