### ISSUE TITLE
share changes for state saving

### ISSUE THREAD

**Issue by Beliwars** [ngraziano/LMICPP-Arduino#4]
Hello @ngraziano, I'm working on a project with ESP32 and LoRa and I'm using Arduino, I was wondering if you have documented the changes you did on LMIC to get the state saving implemented; I would like to do it on the Arduino port of LMIC (I'm ussing MCCI version)
I was trying to follow the changes but if you have documented all it would be better.
For the moment I'm joining every 30 minutes but I would like to use the session info for avoid doing this.

Thanks in advance and regards,

**Comment by ngraziano** [comment]
Hi,
I make a lot of change to LMIC so tracking the change will be hard.

But I can say that to save the state on a LMIC you will have to save :
- a big part of the `struct lmic_t` (all is easier , maybe you can skip `osjob` and `frame` buffer )
- `randbuf`  or re-init it.
